version: '3.8'

services:
  spotify-friend-activity:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spotify-friend-activity
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SP_DC_COOKIE=${SP_DC_COOKIE}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-180000}
    ports:
      - "3000:3000"
    volumes:
      - spotify-logs:/app/logs
      - spotify-data:/app/data
    networks:
      - spotify-network
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spotify.rule=Host(`spotify.localhost`)"
      - "traefik.http.services.spotify.loadbalancer.server.port=3000"

  web-dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spotify-web-dashboard
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SP_DC_COOKIE=${SP_DC_COOKIE}
    ports:
      - "3001:3000"
    volumes:
      - spotify-logs:/app/logs
      - spotify-data:/app/data
    networks:
      - spotify-network
    command: ["node", "src/web-dashboard.js"]
    depends_on:
      - spotify-friend-activity
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spotify-dashboard.rule=Host(`dashboard.spotify.localhost`)"
      - "traefik.http.services.spotify-dashboard.loadbalancer.server.port=3000"

volumes:
  spotify-logs:
    driver: local
  spotify-data:
    driver: local

networks:
  spotify-network:
    driver: bridge