version: '3.8'

services:
  lila-tracker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: lila-tracker
    restart: unless-stopped
    environment:
      - SP_DC_COOKIE=${SP_DC_COOKIE}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-30000}
      - NODE_ENV=production
      - API_PORT=58429
    expose:
      - "58429"
    volumes:
      - lila_shared_data:/app/shared
      - lila_logs:/app/logs
      - lila_data:/app/data
    command: ["node", "src/lila-tracker.js"]
    networks:
      - lila-network

  lila-dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: lila-dashboard
    restart: unless-stopped
    environment:
      - SP_DC_COOKIE=${SP_DC_COOKIE}
      - PORT=3000
      - NODE_ENV=production
      - TRACKER_API_URL=http://lila-tracker:58429
    ports:
      - "${DASHBOARD_PORT:-47293}:3000"
    volumes:
      - lila_shared_data:/app/shared
      - lila_logs:/app/logs
      - lila_data:/app/data
    command: ["node", "src/dashboard.js"]
    depends_on:
      - lila-tracker
    networks:
      - lila-network

volumes:
  lila_logs:
    driver: local
  lila_data:
    driver: local
  lila_shared_data:
    driver: local

networks:
  lila-network:
    driver: bridge
