version: '3.8'

services:
  lila-tracker:
    image: lila-tracker:latest
    container_name: lila-tracker
    restart: unless-stopped
    environment:
      - SP_DC_COOKIE=${SP_DC_COOKIE}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-30000}
      - NODE_ENV=production
    volumes:
      - lila_logs:/app/logs
      - lila_data:/app/data
      - lila_activity_log:/app/lila-activity-log.json
    command: ["node", "src/lila-tracker.js"]
    networks:
      - lila-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  lila-dashboard:
    image: lila-tracker:latest
    container_name: lila-dashboard
    restart: unless-stopped
    environment:
      - SP_DC_COOKIE=${SP_DC_COOKIE}
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3001:3000"
    volumes:
      - lila_logs:/app/logs
      - lila_data:/app/data
      - lila_activity_log:/app/lila-activity-log.json
    command: ["node", "src/dashboard.js"]
    depends_on:
      - lila-tracker
    networks:
      - lila-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  lila_logs:
    driver: local
  lila_data:
    driver: local
  lila_activity_log:
    driver: local

networks:
  lila-network:
    driver: bridge
