version: '3.8'

services:
  spotify-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: spotify-friend-activity
    restart: unless-stopped
    environment:
      - SP_DC_COOKIE=${SP_DC_COOKIE}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-180000}
      - NODE_ENV=production
    volumes:
      - spotify_logs:/app/logs
      - spotify_data:/app/data
    networks:
      - spotify_net
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=false"

  spotify-dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: spotify-web-dashboard
    restart: unless-stopped
    environment:
      - SP_DC_COOKIE=${SP_DC_COOKIE}
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3001:3000"
    volumes:
      - spotify_logs:/app/logs
      - spotify_data:/app/data
    networks:
      - spotify_net
    command: ["node", "src/web-dashboard.js"]
    depends_on:
      - spotify-monitor
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spotify-dashboard.rule=Host(`spotify.yourdomain.com`)"
      - "traefik.http.services.spotify-dashboard.loadbalancer.server.port=3000"

volumes:
  spotify_logs:
  spotify_data:

networks:
  spotify_net:
    driver: bridge
